name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build and Test
        # build task includes testing
        run: ./gradlew build